import Head from 'next/head'
import Image from 'next/image'
import Homepage from '../components/Home/Homepage'
import styles from '../styles/Home.module.css'
import {auth} from '../firebase'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import SignIn from '../components/SignIn'

const Main = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard | Coach Me </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Homepage />
      </div>
    </div>
  )
}

const Home = () => {
  const user = auth.currentUser;
  // console.log(user);

  if (user) {
    return <Main />
  } else {
    return <SignIn />
  }

}

export default Home;